repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
  - repo: local
    hooks:
    -   id: pylint-dags
        name: pylint-dags
        entry: env PYTHONPATH=plugins pylint
        language: system
        exclude: |
          dags/(?x)(
            sentinel_2_nrt/|
            bar/
          )
        files: dags/
        types: [python]
        args: ["--load-plugins=pylint_airflow", "--disable=C,W", "--disable=similarities"]
    -   id: pylint-dags-sentinel2
        name: pylint-dags-sentinel2
        entry: env PYTHONPATH=dags pylint
        language: system
        files: |
          dags/(?x)(
            sentinel_2_nrt/|
            bar/
          )
        types: [python]
        args: ["--load-plugins=pylint_airflow", "--disable=C,W", "--disable=similarities"]
