name: Airflow Lint DAGs

on:
  push:
    paths:
      - 'dags/**'
      - 'scripts/**'
      - '.github/workflows/**'
  pull_request:
    branches:
      - master
      - develop
    paths:
      - 'dags/**'
      - 'scripts/**'
      - '.github/workflows/**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6]
    name: Airflow ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v2
      - name: Install Airflow and Lint
        uses: s-weigand/setup-conda@v1
        with:
          update-conda: true
          python-version: ${{ matrix.python-version }}
          conda-channels: anaconda, conda-forge
      - run: conda --version
      - run: which python
      - run: |
          pwd
          pip install apache-airflow[aws,kubernetes,postgres,redis,ssh,celery]==1.10.11
          pip install pylint pylint-airflow
          pylint --load-plugins=pylint_airflow --disable=C,W --disable=similarities dags
      - run: |
          export AIRFLOW__CORE__DAGS_FOLDER="~/airflow/dags"
          airflow initdb
          airflow connections --add --conn_id aws_nci_db_backup --conn_type aws --conn_login AWSKEY --conn_password AWS_PASS
          airflow connections --add --conn_id lpgs_gadi --conn_type ssh --conn_login USERNAME --conn_password PASS
          airflow info
          airflow list_dags
